name: 'Convert Obsidian to GitHub Wiki'
description: 'A GitHub Action to convert Obsidian notes to the GitHub Wiki format, and push to the wiki repository.'
inputs:
  convert-full-vault:
    description: 'Whether to convert the entire vault or only the files changed in the last commit. (true/false)'
    required: false
    default: 'false'
branding:
  icon: 'book-open'
  color: 'white'
runs:
  using: 'composite'
  steps:
    - name: 'Checkout the repository'
      uses: 'actions/checkout@v6'
      with:
        repository: abredall/vault-to-wiki
        path: 'vault-to-wiki'

    - name: 'Checkout the Obsidian vault'
      uses: 'actions/checkout@v6'
      with:
        path: 'obsidian-vault'
    
    - name: Set up python
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"

    - name: 'Convert Obsidian notes to GitHub Wiki format'
      run: 'python vault-to-wiki/obsidian-to-github-wiki.py --input obsidian-vault --output ./wiki --convert-full-vault ${{ inputs.convert-full-vault }}'
      shell: bash

    - name: 'Push to GitHub Wiki repository'
      run: |
        git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki-repo
        [[ "${CONVERT_FULL_VAULT,,}" =~ ^(true|t|yes|y|1)$ ]] && cd wiki-repo && git rm -rf * && cd ..
        cp -r ./wiki/* wiki-repo/
        cd wiki-repo
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update wiki from Obsidian vault"
        git push
      env:
        CONVERT_FULL_VAULT: ${{ inputs.convert-full-vault }}
      shell: bash